### ISSUE TITLE
challenge in eval.ai

### ISSUE THREAD

**Issue by konyul** [JeffWang987/ASAP#4]
I am wondering if there is a plan about generating a challenge in eval ai website. Thank you

**Comment by JeffWang987** [comment]
> I am wondering if there is a plan about generating a challenge in eval ai website. Thank you

Thanks for your interest in our work! The ASAP contributors are currently occupied with other projects, so the challenge will not be held. However, you are welcome to use ASAP to benchmark streaming perception methods.
